services:
  db:
    image: ankane/pgvector:latest
    container_name: satn_chatbot_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: satn_chatbot
      POSTGRES_USER: satn_admin
      POSTGRES_PASSWORD: Thinuka!@#123
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
